trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
    displayName: 'Use Python 3.11'

  - script: |
      python -m pip install --upgrade pip
    displayName: 'Install dependencies'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-$(python.version).zip
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  
  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: raw_coding_1     
  - script: |
      pip install build
      pip install twine
    displayName: 'Install build and twine'

  - script: |
      python -m build -w
    displayName: 'Python build'

  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: raw_coding_1
    displayName: 'Twine Authenticate'

  - script: |
      python -m twine upload -r raw_coding_1 --config-file $(PYPIRC_PATH) dist/*.whl
    displayName: 'Upload to feed'

